# Site settings
title: Elias Hernandis
email: eliashernandis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aspiring web developer and computer scientist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hernandis.ga" # the base hostname & protocol for your site
lang: en

# social settings
twitter_username: eliashernandis
github_username:  knifecake

# Build settings
markdown: kramdown
