# Site settings
title: Elias Hernandis
email: eliashernandis@gmail.com
author: Elias Hernandis
description: > # this means to ignore newlines until "baseurl:"
  Happy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hernandis.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
